#!/bin/bash

archivo=$1

if [ ! -e $archivo ]; then
        echo "El archivo $nombre no existe.\n"
elif [ -z $archivo ]; then
        echo "Es necesario el nombre del archivo al que quiere cambiar sus permisos.\n"
else

  red="\x1b[38:5:9m"
  lime="\x1b[38:5:10m"
  yellow="\x1b[38:5:11m"
  #yellow="033[1;33m"
  blue="\x1b[38:5:12m"
  white="\x1b[38:5:15m"
  black="\x1b[38:5:16m"
  greyb="\x1b[48:5:250m"
  silverb="\x1b[48:5:7m"
  
  run=1
  while [ $run != 0 ]; do
  
    echo -e "${yellow}Seleccione el usuario al que desea editar sus permisos:"
    echo -e "${red}u${white} usuario"
    echo -e "${red}g${white} grupo"
    echo -e "${red}o${white} otros\n"
    
    read -n1 user
    
    msg=0
    
    while [ $msg != 3 ]; do
    
    case $msg in
    0) echo -e "\nPermisos de lectura? (s/n):";;
    1) echo -e "\nPermisos de escritura? (s/n):";;
    2) echo -e "\nPermisos de ejecucion? (s/n):";;
    esac
    
    read -n1 respuesta
    
    for permiso in r w x; do
    if [ $respuesta = "s" ]; then
            chmod "$user"+"$permiso" "$archivo"
    else
            chmod "$user"-"$permiso" "$archivo"
    fi
    done
    
    msg=`expr $msg + 1`
    done
    
    echo -e "\n{yellow}Desea continuar con la edicion de permisos para el archivo $a
    rchivo?{blue} (s/n){white}:"
    read -n1 continuar
    
    if [ $continuar = "n" ]; then
            run=0
    else
            clear
    fi
    done
    echo -e "\nPermisos de $archivo cambiados con exito."

fi
