#!/bin/bash

archivo="$1"

if [ -z $archivo ]; then
        echo "no hay.\n"
elif [ ! -e $archivo ]; then
        echo "No existe nombre.\n"
else

red="\e[31m"
yellow="\x1b[38;5;10m"
white="\x1b[38;5;15m"
blue="\x1b[38;5;12m"

run=1
while [ $run != 0 ]; do

        echo -e "${yellow}Seleccione el usuario al que desea editar sus permisos:"
        echo -e "${red}u${white} usuario"
        echo -e "${red}g${white} grupo"
        echo -e "${red}o${white} otros\n"

        read -n1 user

        msg=0

        #while [ $msg !=3 ]; do

        for permiso in r w x
        do

        case $msg in
        0) echo -e "\nPermisos de lectura? (s/n): ";;
        1) echo -e "\nPermisos de escritura? (s/n): ";;
        2) echo -e "\nPermisos de ejecucion? (s/n): ";;
        esac

        read -n1 respuesta

        #for permiso in r w x; do
        if [ $respuesta = "s" ]; then
                chmod "$user"+"$permiso" "$archivo"
        else
                chmod "$user"-"$permiso" "$archivo"
        fi
        #done

        msg=`expr $msg + 1`
        done

        echo -e "\n{yellow}Desea continuar con la edicion de permisos para el archivo $archiv
o?{blue} (s/n){white}:"
        read -n1 continuar

        if [ $continuar = "n" ]; then
                run=0
        else
                clear
        fi
        done
        echo -e "\nPermisos de $archivo cambiados con exito."
fi
